# name of the serverless service
service: portfolio

provider:
  name: aws
  runtime: python3.8 
  stage: test
  region: eu-central-1

functions:
  randomNumber:
    handler: src/handler.handle
    name: reandomNumber

# https://www.serverless.com/framework/docs/providers/aws/guide/packaging/
package:
  patterns:
    - "!**"
    - "src/**"