# name of the serverless service
service: portfolio

provider:
  name: aws
  runtime: python3.8 
  stage: test
  region: eu-central-1

functions:
  randomNumber:
    name: getReandomNumber
    handler: src/handler.handle
    

# https://www.serverless.com/framework/docs/providers/aws/guide/packaging/
#package:
#  patterns:
#    - "!**"
#    - "src/**"

package:
  individually: true
  exclude:
    # exclude everything
    - "**/*"